name: dio_http_cache
description: http cache lib for Flutter dio like RxCache.It use sqflite as disk cache,and google/quiver-dart/LRU strategy as memory cache.
version: 0.3.0


environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.3
  dio: ^5.3.3
  flutter:
    sdk: flutter
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  path: ^1.8.3
  quiver: ^3.2.1
  sqflite: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter

flutter:
  module:
    androidX: true
